#! /bin/bash

eeprom="/usr/share/boardinfo/tmpeeprom"
boardinfo="/usr/share/boardinfo/boardinfo_cfg"
inventoryconfig="/usr/share/entity-manager/configurations/zvezda-baseboard.json"

inventory()
{   
    if [[ -r $boardinfo ]]; then
        model=$(grep 'Iridium' $boardinfo)
        sn=$(grep 'IR-' $boardinfo)
        pn=$(grep '24-' $boardinfo)

        busctl set-property xyz.openbmc_project.EntityManager \
         /xyz/openbmc_project/inventory/system/board/Zvezda_Iridium_Baseboard \
          xyz.openbmc_project.Inventory.Decorator.Asset Model s $model

        busctl set-property xyz.openbmc_project.EntityManager \
         /xyz/openbmc_project/inventory/system/board/Zvezda_Iridium_Baseboard \
          xyz.openbmc_project.Inventory.Decorator.Asset SerialNumber s $sn

        busctl set-property xyz.openbmc_project.EntityManager \
         /xyz/openbmc_project/inventory/system/board/Zvezda_Iridium_Baseboard \
          xyz.openbmc_project.Inventory.Decorator.Asset PartNumber s $pn

#        sethostname $sn $1
    fi
}

sethostname()
{
    tmp=$(echo $2 | tr -d ':')
    hostnamectl set-hostname $1-$tmp
}

setmac() 
{
    echo "Start changing for $2 ..."
    if [[ -r $boardinfo ]]; then
        ifconfig $2 down
        sleep 5
        busctl set-property xyz.openbmc_project.Network \
        /xyz/openbmc_project/network/$2 \
        xyz.openbmc_project.Network.MACAddress \
        MACAddress s $1 
        sleep 5
        ifconfig $2 up
    fi
}

initfs()
{
    mkdir /usr/share/boardinfo
    echo Zvezda >> $boardinfo
    echo Iridium224X >> $boardinfo
    echo 52:54:00:12:34:70::52:54:00:12:34:71 >> $boardinfo
    echo IR-224X-00002 >> $boardinfo
    echo 24-47G32 >> $boardinfo
}

if [[ ! -r $boardinfo ]]; then
    initfs
fi

if [[ $1 == "--chmac" ]]; then
    macfield=$(grep '..:..:..:..:..:..' $boardinfo)
    mac1=${macfield:0:17}
    mac2=${macfield:19}

    setmac $mac1 eth0
#    setmac $mac2 eth1
    
    echo "Please de-energize chassis"
fi

inventory $(cat /sys/class/net/eth0/address)
