0x50:
  /system/chassis/motherboard:
    entityID: 7
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
  /system:
    entityID: 23
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Chassis
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Chassis
        Model:
          IPMIFruProperty: Type
          IPMIFruSection: Chassis
